#!/bin/sh
# Assign ownership of the console to the invoking user
# $Xorg: GiveConsole,v 1.3 2000/08/17 19:54:17 cpqbld Exp $
#
# By convention, both xconsole and xterm -C check that the
# console is owned by the invoking user and is readable before attaching
# the console output.  This way a random user can invoke xterm -C without
# causing serious grief.
#
chown $USER /dev/console
pid=$(cat /var/run/xdmshutdown.pid 2>/dev/null)
test "$pid" && kill -9 $pid 2>/dev/null
