#!/bin/sh
# Register a login (derived from GiveConsole as follows:)
#

# put me in /usr/local/lib/X11/xdm
echo "running Xstartup" > /tmp/xstartup
pid=$(cat /var/run/xdmshutdown.pid 2>/dev/null)
test "$pid" && kill -9 $pid 2>/dev/null

/usr/local/bin/sessreg  -a -w "/var/log/wtmp" -u "/var/run/utmp" 	-x "/usr/local/lib/X11/xdm/Xservers" -l $DISPLAY -h "" $USER
