#!/bin/sh
#
# $XdotOrg: $
# $Xorg: Xsession,v 1.4 2000/08/17 19:54:17 cpqbld Exp $
# $XFree86: xc/programs/xdm/config/Xsession,v 1.2 1998/01/11 03:48:32 dawes Exp $

# redirect errors to a file in user's home directory if we can

errfile="$HOME/.xsession-errors"
if ( umask 077 && cp /dev/null "$errfile" 2> /dev/null )
then
	exec > "$errfile" 2>&1
else

	mktemp=/usr/bin/mktemp
	for errfile in "${TMPDIR-/tmp}/xses-$USER" "/tmp/xses-$USER"
	do
		if ef="$( umask 077 && $mktemp "$errfile.XXXXXX" 2> /dev/null)"
		then
			exec > "$ef" 2>&1
			mv "$ef" "$errfile" 2> /dev/null
			break
		fi
	done
fi

case $# in
1)
	case $1 in
	failsafe)
		exec /usr/local/bin/xterm -geometry 80x24-0-0
		;;
	esac
esac

# The startup script is not intended to have arguments.

startup=$HOME/.xsession
resources=$HOME/.Xresources

if [ -s "$startup" ]; then
	if [ -x "$startup" ]; then
		exec "$startup"
	else
		exec /bin/sh "$startup"
	fi
else
	if [ -r "$resources" ]; then
		/usr/local/bin/xrdb -load "$resources"
	fi
	# exec /usr/local/bin/xsm
	exec /usr/local/bin/gnome-session
fi

