#!/bin/sh
# $Xorg: Xsetup_0,v 1.3 2000/08/17 19:54:17 cpqbld Exp $

# put me in /usr/local/lib/X11/xdm
#/usr/local/bin/xsetroot -solid steelblue
/usr/local/bin/xv -root -quit /usr/local/lib/X11/xdm/pixmaps/bsd_background.jpg
/usr/local/sbin/xdmshutdown -geometry +50+680 &
echo $! > /var/run/xdmshutdown.pid
