#!/bin/sh -e

##########################################################################
#   Description:
#       NetBSD desktop-installer
#
#   History:
#   Date        Name        Modification
#   2023-06-10  Charlie &,,,Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Create a global Xsession file
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2023-06-13  Charlie &,,,Begin
##########################################################################

create_xsession()
{
    if [ $# != 1 ]; then
	printf "Usage: create_xsession session-command\n"
	exit 1
    fi
    session_cmd=$1
    
    # FIXME: Use auto-something
    if [ ! -e $XSESSION.ctwm ]; then
	mv $XSESSION $XSESSION.ctwm
    fi
    
    # Need ck-launch for consolekit to function
    cat << EOM > $XSESSION
#!/bin/sh

exec ck-launch-session dbus-launch --exit-with-session $session_cmd
EOM
    
    cat << EOM > $HOME/.xinitrc
#!/bin/sh -e

exec ck-launch-session dbus-launch --exit-with-session $session_cmd
EOM

    auto-append-line 'DisplayManager*authName' \
	'DisplayManager*authName: MIT-MAGIC-COOKIE-1' $XDM_CONF nocomment
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

# Should have been installed as a dep, but just in case
pkgin -y install auto-admin
pkgin -y install digest fetch git cvs gmake xz feh tk consolekit

if ! auto-package-installed security/mozilla-rootcerts-openssl; then
    printf "Install mozilla root certs? (Needed to access many sites) [y]/n "
    read mz
    if [ 0$"mz" != 0n ]; then
	pkgin -y install mozilla-rootcerts-openssl
    fi
fi

for base_set in comp man xbase xetc xcomp xfont xserver; do
    if [ ! -e /etc/mtree/set.$base_set ]; then
	printf "Installing $set...\n"
	auto-install-base-components $base_set
    else
	printf "$base_set already installed.\n"
    fi
done

if [ ! -e /usr/pkgsrc ]; then
    printf "Installing pkgsrc tree...\n"
    cd /usr
    ftp ftp://ftp.netbsd.org/pub/pkgsrc/stable/pkgsrc.tar.xz
    tar -zxvf pkgsrc.tar.xz
fi

if [ ! -e /usr/pkgsrc/wip ]; then
    printf "Install pkgsrc-wip? y/[n] "
    read wip
    if [ 0"$wip" = 0y ]; then
	cd /usr/pkgsrc
	auto-pkgsrc-wip-checkout
    fi
fi

cat << EOM

1.. CTWM (NetBSD default)
2.. Gnome
3.. KDE
4.. LXDE
5.. LXQT
6.. MATE
7.. XFCE
8.. Custom

EOM
printf "Selection? "
read de

XDM_CONF=/etc/X11/xdm/xdm-config
XSESSION=/etc/X11/xdm/Xsession

case $de in
1)
    if [ -e $XSESSION.ctwm ]; then
	mv -f $XSESSION.ctwm $XSESSION
    fi
    pkgin -y install evince
    rm $HOME/.xinitrc
    ;;

2)
    pkgin -y install gnome evince
    create_xsession gnome-session
    ;;

3)
    pkgin -y install kde
    create_xsession startkde
    ;;

4)
    pkgin -y install lxde evince
    create_xsession startlxde
    ;;

5)
    pkgin -y install lxqt evince
    create_xsession lxqt-session
    ;;

6)
    pkgin -y install mate evince
    create_xsession mate-session
    ;;

7)
    pkgin -y install xfce4 evince
    create_xsession xfce4-session
    ;;

8)
    printf "Package name? (Use pkgin search to verify) "
    read package
    printf "Session command? (See category/$package/PLIST) "
    read session_cmd
    
    pkgin -y install $package
    create_xsession $session_cmd
    ;;
    
*)
    printf "Invalid selection.\n"
    exit 1
    ;;

esac

##########################################################################
#   From guide
##########################################################################

cp /usr/pkg/share/examples/rc.d/dbus /etc/rc.d
# FIXME: Use auto-enable-service
auto-enable-service dbus $0

# Enhanced XDM with background and restart/shutdown/restart-x11 buttons
auto-replace-file /usr/pkg/share/desktop-installer/XDM/Xsetup_0 /etc/X11/xdm/Xsetup_0
auto-replace-file /usr/pkg/share/desktop-installer/XDM/GiveConsole /etc/X11/xdm/GiveConsole

cat << EOM

Enabling XDM will cause the screen to switch to graphics mode.

If you are running desktop-installer on the primary text console,
you can return to the text console by typing Ctrl+Alt+F1 on most
systems (or Meta-key + F1 under VirtualBox).

EOM
printf "Enable XDM graphical login? [y]/n "
read xdm
if [ 0"$xdm" != 0n ]; then
    auto-enable-service xdm $0
fi

for app in www/firefox mail/thunderbird security/keepassxc; do
    if ! auto-package-installed $app; then
	printf "Install $app? y/[n] "
	read install
	if [ 0"$install" = 0y ]; then
	    apps="$apps ${app#*/}"
	fi
    fi
done
if [ ! -z "$apps" ]; then
    pkgin -y install $apps
fi
