#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/local/lib/X11/xinit/.Xresources
sysmodmap=/usr/local/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# FIXME: Should this be necessary, or is it a WM responsibility?
if sysctl dev.acpi.0.%desc | fgrep -q VBOX; then
    # VBoxClient is part of guest additions, which may not be installed
    VBoxClient --display || true
fi

aa_dir=/usr/local/etc/auto-admin
for local_xsession in $aa_dir/xsession.*; do
    if [ -e  ] && /usr/local/sbin/auto-file-secure $local_xsession; then
	. $local_xsession
    fi
done

exec icewm-session
